### ISSUE TITLE
Janitor deletes data only containers and images 

### ISSUE THREAD

**Issue by Mrono** [meltwater/docker-cleanup#18]
I had to re-create my entire environment

**Comment by mikljohansson** [comment]
Very sorry to hear that! 

The first sentence of the readme does say "This image will periodically clean up exited containers and remove images and volumes that aren't in use by a running container." but that might not be enough. Perhaps we should include more of a warning like https://github.com/chadoe/docker-cleanup-volumes does, highlighting what the container will do?

**Comment by Mrono** [comment]
It happens, not upset.

I installed via the rancher catalog, which may not have that warning (still my fault for not investigating it more).  The issue is that the cleanup doesn't make a distinction between stopped containers, and stopped data-only containers.

**Comment by mikljohansson** [comment]
I've added a warning in bold text to the readme, let's hope others don't end up with the same issues. 

When using exited containers to hold data I think this cleanup image might not be the best thing to have running in a cluster, even if carefully excluding them with $KEEP_CONTAINERS. Since it could be prone to mistakes and wipe out valuable data.

Didn't know that this image was in rancher catalog, is that a curated repository and where could I find it? (Google didn't help much in finding it..)

About data-only containers, is there a way to distinguish them from regular existed containers?

**Comment by Mrono** [comment]
https://github.com/sshipway/rancher-catalogue/tree/master/templates/janitor

**Comment by mikljohansson** [comment]
Interesting, will take a closer look. In any case, thanks for reporting this
