### ISSUE TITLE
delay on start

### ISSUE THREAD

**Issue by tj** [meltwater/docker-cleanup#2]
seems that if you use --restart=always it'll start removing others that haven't restarted yet, some extra info in the logs would be nice too right now there's just the id so it's hard to see what happened

**Comment by mikljohansson** [comment]
Not sure I entirely follow you, do you means that it removes containers
that are in the process of restarting?

We'd be most happy to accept PRs for additional logging and some filtering
for restart=always containers.

Perhaps it might be difficult to implement in bash in case docker inspect
needs to be used. We've been considering adding container cleanup to the
new golang version of tutum/image-cleanup, whose original shell script
docker-cleanup is copied from.

**Comment by tj** [comment]
Yeah that seems to be the case, usually it takes out one or two that we have as restart=always. A Go version would be great, if I can get some time I'll try and help out there!

**Comment by mikljohansson** [comment]
Have you looked into tutumcloud/cleanup? Perhaps it can fill your usecase,
its a golang version of docker-cleanup. Difference is that it doesn't
remove exited containers.

https://github.com/tutumcloud/cleanup

I've been considering trying to add exited-container cleanup to it and
scrapping this bash script. We're also not using restart=always, instead
relying on systemd or Marathon to restart services. This unfortunately also
means that it's unlikely we'd spend significant time adding explicit
handling for restart=always containers.

However we'd be happy to accept a PR if it's not complex, otherwise perhaps
adding it to tutumcloud/cleanup may be a better option.

**Comment by tj** [comment]
fair enough! I will take a look
