### ISSUE TITLE
KEEP_VOLUMES

### ISSUE THREAD

**Issue by pschrammel** [meltwater/docker-cleanup#32]
Hi,

I have some cuda (nvidia volumes) that should always stay around. Is there a possibility to keep them?

**Comment by sorenroug** [comment]
I came here to request the same. Since it is now possible to create named volumes as in `docker volume create --name project1-files` it would be great if it was possible to keep some by name.
Another problem I have is that the clean ignores the driver. On a random host I would see this:

```
$ docker volume ls
DRIVER              VOLUME NAME
local               etcdd-mysql
local               papers-aqr-logs
local               ce7574cd1e4d647b9796ac6e2f88196fb989d38b375431483043438f260f8568
local               etcdd-apps
local               etcdd-files
convoy-mil          jabber-backup
convoy-mil          jabber-logs
convoy-mil          forum-mailqueue
convoy-mil          forum-ldapdump
convoy-mil          forum-test-ldapdump
```

Those with the `convoy-mil` are shared and are probably not used on that host so a remove is attempted. Luckily the attempt is ignored, but it is disconcerting to see remove attempts. Could the script made to only work on volumes with the `local` driver?

**Comment by rasjoh** [comment]
Won't fix due to retiring project
